Fixed exception
Was generating an exception "ERROR [TypeError]: __new__() missing 1 required positional argument: 'RoleSessionName'"
when not running within a RoleSessionName